### PR TITLE
ArduinoOnRampAlarm

### PR DESCRIPTION
**Pull request by lemgandi**
Added "ArduinoOnRampAlarm" in the "Code" section.  This version alarms for about 25 seconds, then re-arms.  If you #define RANGE_POT, you can add a potentiometer on pin A4 to control how close you have to be to the sonar before it will pop.  Otherwise, I assume 10 cm.

### CODE REVIEW

**Comment by haleyma** [comment]
Great!  Charles can we change the name of your .ino file?  Just to keep it distinct from the one's I've created (which are not all on this repository).  Thanks.  Maybe add Shapiro to the end or something?

**Comment by lemgandi** [comment]
Sure NP.  Let me know and I'll change it on my fork.

**Comment by haleyma** [comment]
Charles, this is great!  I'm going to include your changes in ArduinoOnRampRed2 without the potentiometer.  Would you please consider making a separate sketch with the pot and the timeout and the LED code , renaming it and then I'll put it in the code file as a separate sketch.  Thanks.   Oh, I struggle still with making line by line changes in git, so I've done the changes in my Arduino IDE and will upload to github.

**Comment by lemgandi** [comment]
Um.  Sure, I _could_ do that.  The potentiometer code is controlled by an
#ifdef in the top of the file.  If the #RANGE_POT macro is commented out
(as it is in the repo), the sketch will build and run without referencing
the range potentiometer, with a fixed alarm range of 10 cm. Un-comment the
macro if you've got the range control wired in. This is the usual way the
Cool Kids handle code that has to compile for different hardware or
different platforms.  It makes the program a little harder to read, but
assuming that I've figured out what needs to change correctly it means that
you don't have to, like, do that.

I'm a little reluctant to make a whole separate sketch, since that means
that I'll have to replicate any changes or improvements to the other one in
the second one manually.  That pretty much guarantees that the two sketches
will diverge over time, perhaps in unpleasant ways.

How 'bout I just rename "ArduinoOnRampAlarm" to "ArduinoOnRampAlarmCHS" in
my repo and do a pull request?

**Comment by haleyma** [comment]
I like your solution.  Thanks for your patience as I am learning to work with github.

 

Maureen

**Comment by lemgandi** [comment]
Add ArduinoOnRampAlarmCHS, as we discussed.

**Pull request closed without merging**
